import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/Home.module.css'
import TabBar from '../../components/ui/organisms/tabBar/TabBar'
import DetailsArea from '../../components/ui/organisms/detailsArea/DetailsArea'

export default function Details () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by Baris' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='container'>
        <TabBar />
      </div>
      <main className={`container ${styles.main}`}>
        <DetailsArea />
      </main>
    </div>
  )
}
