import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/Home.module.css'
import TabBar from '../../components/ui/organisms/tabBar/TabBar'
import ListArea from '../../components/ui/organisms/listArea/ListArea'

export default function List () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by Baris' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='container'>
        <TabBar />
      </div>
      <main className={`container ${styles.main}`}>
        <ListArea />
      </main>
    </div>
  )
}
