import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/Home.module.css'
import TabBar from '../../components/ui/organisms/tabBar/TabBar'

export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Asset List</title>
        <meta name='description' content='Generated by Baris' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='container'>
        <TabBar />
      </div>
      <main className={styles.main}>
        <h1 className='text-white'>Asset List</h1>
      </main>
    </div>
  )
}
