import Head from 'next/head'
import Navbar from '../components/ui/organisms/navbar/Navbar'
import Searchbox from '../components/ui/organisms/searchbox/Searchbox'
import Row2Cols from '../components/templates/row2Cols/Row2Cols'

import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/Home.module.css'
import Numbers from '../components/ui/organisms/widgets/numbers/Numbers'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Landing Page</title>
        <meta name='description' content='Generated by Baris' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <div id='main' className='container-fluid'>
        <Searchbox />

        <Numbers />

        <Row2Cols />
      </div>

      {/* <div className='container'>
        <TabBar />
      </div>
      <main className={`container ${styles.main}`}>
        <SearchArea />
      </main> */}
    </div>
  )
}

export default Home
