import Head from 'next/head'
import SearchArea from '../components/ui/organisms/searchArea/SearchArea'
import TabBar from '../components/ui/organisms/tabBar/TabBar'

import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/Home.module.css'
import Navbar from '../components/ui/organisms/navbar/Navbar'
import Searchbox from '../components/ui/organisms/searchbox/Searchbox'
import Widgetsbox from '../components/ui/organisms/widgetsbox/Widgetbox'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Landing Page</title>
        <meta name='description' content='Generated by Baris' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <div id='main'>
        <Searchbox />

        <Widgetsbox />
      </div>

      {/* <div className='container'>
        <TabBar />
      </div>
      <main className={`container ${styles.main}`}>
        <SearchArea />
      </main> */}
    </div>
  )
}

export default Home
