import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Asset List App</title>
        <meta name='description' content='Generated by Baris' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main} />
    </div>
  )
}
